# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_name',
            field=models.CharField(default='', max_length=128, verbose_name='\u0418\u043c\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_surname',
            field=models.CharField(default='', max_length=128, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
